from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet


def generate_prediction_pdf(prediction, shap=None) -> bytes:
    """
    Generates a PDF report for a prediction row (dictionary form).
    Returns the PDF bytes.
    """

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    elements = []

    # Title
    elements.append(Paragraph("<b>GBS Subtype Prediction Report</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    # Subtype
    elements.append(Paragraph(f"<b>Predicted Subtype:</b> {prediction['predicted_subtype']}", styles["Heading2"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {(prediction['confidence']*100):.1f}%", styles["Normal"]))
    elements.append(Spacer(1, 12))

    # Probabilities table
    prob_data = [["Subtype", "Probability (%)"]]
    for subtype, value in prediction["probabilities"].items():
        prob_data.append([subtype, f"{value*100:.1f}%"])

    prob_table = Table(prob_data)
    prob_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN", (1, 1), (-1, -1), "CENTER")
    ]))

    elements.append(Paragraph("<b>Probability Distribution</b>", styles["Heading3"]))
    elements.append(prob_table)
    elements.append(Spacer(1, 18))

    # SHAP section
    if shap:
        elements.append(Paragraph("<b>Top SHAP Feature Importance</b>", styles["Heading3"]))

        shap_data = [["Feature", "Impact"]]
        for feature, impact in shap.get("ranked_importance", [])[:8]:
            shap_data.append([feature, f"{impact:.4f}"])

        shap_table = Table(shap_data)
        shap_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))

        elements.append(shap_table)
        elements.append(Spacer(1, 18))
    else:
        elements.append(Paragraph("<i>SHAP explainability was not available.</i>", styles["Normal"]))
        elements.append(Spacer(1, 18))

    # End text
    elements.append(Paragraph(
        "This report was automatically generated by the GBS Subtype Decision Support System.",
        styles["Italic"]
    ))

    doc.build(elements)
    return buffer.getvalue()
